CREATE TABLE admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL
);

CREATE TABLE form_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    html_content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE custom_forms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id BIGINT NOT NULL UNIQUE REFERENCES campaigns(id),
    template_id BIGINT NOT NULL REFERENCES form_templates(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE distribution_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id BIGINT NOT NULL REFERENCES campaigns(id),
    channel VARCHAR(255) NOT NULL,
    token VARCHAR(64) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE visitors (
    id VARCHAR(64) PRIMARY KEY,
    first_seen_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id BIGINT NOT NULL REFERENCES campaigns(id),
    distribution_link_id BIGINT NOT NULL REFERENCES distribution_links(id),
    visitor_id VARCHAR(64) NOT NULL REFERENCES visitors(id),
    visited_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id BIGINT NOT NULL REFERENCES campaigns(id),
    distribution_link_id BIGINT NOT NULL REFERENCES distribution_links(id),
    visitor_id VARCHAR(64) NOT NULL REFERENCES visitors(id),
    data TEXT NOT NULL,
    submitted_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_distribution_links_campaign ON distribution_links(campaign_id);
CREATE INDEX idx_visits_campaign ON visits(campaign_id);
CREATE INDEX idx_visits_distribution_link ON visits(distribution_link_id);
CREATE INDEX idx_leads_campaign ON leads(campaign_id);
CREATE INDEX idx_leads_distribution_link ON leads(distribution_link_id);
